-- Create the database
CREATE DATABASE IF NOT EXISTS DWH_PROJECT;

-- Switch context to the new database
USE DATABASE DWH_PROJECT;

-- Create the three schemas
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

